# Generated by Django 5.0.7 on 2024-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_search',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city_search',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
